---
# Source: example-app-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-app
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
---
# Source: example-app-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app: example-app
  annotations:
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: guybalmas/example-app:b9.20220713.115621  # {"$imagepolicy": "flux-system:example-app"}
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:NativeMemoryTracking=off"
            - name: "BPL_JAVA_NMT_ENABLED"
              value: "false"
            - name: "GREETING_MSG"
              value: Welcome to Kpack + Flux demo!!!!!!@#*
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
#            limits:
#              memory: "1000Mi"
#              cpu: "1000m"
