name: chart handler example

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - run: git config user.name "GITHUB_USER"
      - run: cd example-app
      - run: helm template ./chart > ./manifest/manifest.yaml
      - run: git add .
      - run: git commit -m "pushed manifest due to chart change"
      - run: git push
