name: chart handler example

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Push Helm Chart to ChartMuseum
        uses: bsord/helm-push@4.1.0
        with:
          username: 'github.bot'
          password: 'password'
          registry-url: 'https://172.17.16.1:9090'
          force: true
          chart-folder: ./chart

      - run: git config user.name "flux.user"
      - run: cd /home/runner/work/example-app/example-app
      - run: ls -a
      - run: helm template ./chart > ./manifest/manifest.yaml
      - run: git add .
      - run: git commit -m "pushed manifest due to chart change"
      - run: git push

